// Datos del menú extraídos de las imágenes
export const menuData = [
  // ENTRANTES / STARTERS
  {
    id: 1,
    number: '01',
    category: 'ENTRANTES',
    categoryEn: 'STARTERS',
    nameEs: 'Ensalada china',
    nameEn: 'Chinese salad',
    descriptionEs: 'Ensalada iceberg, zanahorias, maíz y salsa blanca',
    descriptionEn: 'Iceberg lettuce, carrots, chopped corn, and white dressing',
    price: 2.95,
    quantity: null
  },
  {
    id: 2,
    number: '02',
    category: 'ENTRANTES',
    categoryEn: 'STARTERS',
    nameEs: 'Ensalada verdura mixta',
    nameEn: 'Mixed vegetable salad',
    descriptionEs: 'de repollo, zanahoria y cebolla con mayonesa',
    descriptionEn: 'cabbage, carrot, and onion with mayonnaise',
    price: 2.95,
    quantity: null
  },
  {
    id: 3,
    number: '03',
    category: 'ENTRANTES',
    categoryEn: 'STARTERS',
    nameEs: 'Edamame cocido con sal',
    nameEn: 'Edamame boiled in salted water',
    descriptionEs: '',
    descriptionEn: '',
    price: 2.95,
    quantity: null
  },
  {
    id: 4,
    number: '04',
    category: 'ENTRANTES',
    categoryEn: 'STARTERS',
    nameEs: 'Ensalada de patata en tallarines',
    nameEn: 'Potato salad noodles',
    descriptionEs: 'con zanahoria un poco de picante',
    descriptionEn: 'with carrots and a little spice',
    price: 2.95,
    quantity: null
  },
  {
    id: 5,
    number: '05',
    category: 'ENTRANTES',
    categoryEn: 'STARTERS',
    nameEs: 'Rollito de primavera vegetal',
    nameEn: 'Vegetable Spring roll',
    descriptionEs: '',
    descriptionEn: '',
    price: 3.95,
    quantity: null
  },
  {
    id: 6,
    number: '06',
    category: 'ENTRANTES',
    categoryEn: 'STARTERS',
    nameEs: 'Rollito de langostino y mango',
    nameEn: 'Shrimp and mango spring roll',
    descriptionEs: '',
    descriptionEn: '',
    price: 5.95,
    quantity: null
  },
  // MO XIAN
  {
    id: 11,
    number: '11',
    category: 'MO XIAN',
    categoryEn: 'MO XIAN',
    nameEs: 'Mò XIAN de carne',
    nameEn: 'XIAN meat Mó',
    descriptionEs: 'pan crujiente relleno de cerdo estofado con cebolla y pimiento verde',
    descriptionEn: 'crispy bread with pork stewed with onion and green pepper',
    price: 5.50,
    quantity: null
  },
  // GYOZAS A LA PLANCHA
  {
    id: 21,
    number: '21',
    category: 'GYOZAS A LA PLANCHA',
    categoryEn: 'GRILLED GYOZAS',
    nameEs: 'Gyozas de pollo y verdura',
    nameEn: 'Chicken and vegetable gyozas',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.50,
    quantity: '10 uds.'
  },
  {
    id: 22,
    number: '22',
    category: 'GYOZAS A LA PLANCHA',
    categoryEn: 'GRILLED GYOZAS',
    nameEs: 'Gyozas de carne y verdura',
    nameEn: 'Meat and vegetable gyozas',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.50,
    quantity: '10 uds.'
  },
  {
    id: 23,
    number: '23',
    category: 'GYOZAS A LA PLANCHA',
    categoryEn: 'GRILLED GYOZAS',
    nameEs: 'Gyozas de ternera y verdura',
    nameEn: 'Beef and vegetable gyozas',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.95,
    quantity: '10 uds.'
  },
  {
    id: 24,
    number: '24',
    category: 'GYOZAS A LA PLANCHA',
    categoryEn: 'GRILLED GYOZAS',
    nameEs: 'Gyozas de verdura y fideo',
    nameEn: 'Vegetable and noodle gyozas',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.50,
    quantity: '10 uds.'
  },
  {
    id: 25,
    number: '25',
    category: 'GYOZAS A LA PLANCHA',
    categoryEn: 'GRILLED GYOZAS',
    nameEs: 'Gyozas de langostino y verdura',
    nameEn: 'Prawn and vegetable gyozas',
    descriptionEs: '',
    descriptionEn: '',
    price: 7.95,
    quantity: '10 uds.'
  },
  {
    id: 26,
    number: '26',
    category: 'GYOZAS A LA PLANCHA',
    categoryEn: 'GRILLED GYOZAS',
    nameEs: 'Gyozas de ibérico y seta',
    nameEn: 'Iberian and mushroom gyozas',
    descriptionEs: '',
    descriptionEn: '',
    price: 9.95,
    quantity: '10 uds.'
  },
  // GYOZAS FRITAS
  {
    id: 31,
    number: '31',
    category: 'GYOZAS FRITAS',
    categoryEn: 'FRIED GYOZAS',
    nameEs: 'Gyozas de carne y verdura',
    nameEn: 'Meat and vegetable gyozas',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.50,
    quantity: '10 uds.'
  },
  {
    id: 32,
    number: '32',
    category: 'GYOZAS FRITAS',
    categoryEn: 'FRIED GYOZAS',
    nameEs: 'Gyozas de pollo y verdura',
    nameEn: 'Chicken and vegetable gyozas',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.50,
    quantity: '10 uds.'
  },
  // GYOZAS AL VAPOR
  {
    id: 41,
    number: '41',
    category: 'GYOZAS AL VAPOR',
    categoryEn: 'STEAMED GYOZAS',
    nameEs: 'Gyozas de carne y verdura',
    nameEn: 'Meat and vegetable gyozas',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.50,
    quantity: '10 uds.'
  },
  {
    id: 42,
    number: '42',
    category: 'GYOZAS AL VAPOR',
    categoryEn: 'STEAMED GYOZAS',
    nameEs: 'Gyozas de pollo y verdura',
    nameEn: 'Chicken and vegetable gyozas',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.50,
    quantity: '10 uds.'
  },
  {
    id: 43,
    number: '43',
    category: 'GYOZAS AL VAPOR',
    categoryEn: 'STEAMED GYOZAS',
    nameEs: 'Gyozas de langostino y verdura',
    nameEn: 'Shrimp and vegetable gyozas',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.95,
    quantity: '10 uds.'
  },
  // DIMSUM
  {
    id: 51,
    number: '51',
    category: 'DIMSUM',
    categoryEn: 'DIMSUM',
    nameEs: 'BAO de carne Shanghainés',
    nameEn: 'Shanghainese meat BAO',
    descriptionEs: '',
    descriptionEn: '',
    price: 5.95,
    quantity: '4 uds.'
  },
  {
    id: 52,
    number: '52',
    category: 'DIMSUM',
    categoryEn: 'DIMSUM',
    nameEs: 'BAO de ibérico con trufa',
    nameEn: 'Iberian BAO with truffle',
    descriptionEs: '',
    descriptionEn: '',
    price: 5.95,
    quantity: '4 uds.'
  },
  {
    id: 53,
    number: '53',
    category: 'DIMSUM',
    categoryEn: 'DIMSUM',
    nameEs: 'Hakao langostino',
    nameEn: 'Hakao prawn',
    descriptionEs: 'relleno de gambas al estilo cantonés',
    descriptionEn: 'Cantonese-style prawn filling',
    price: 5.95,
    quantity: '4 uds.'
  },
  // PARA IR CON TODO
  {
    id: 61,
    number: '61',
    category: 'PARA IR CON TODO',
    categoryEn: 'GO FOR IT',
    nameEs: 'Cerdo agridulce',
    nameEn: 'Sweet and sour pork',
    descriptionEs: '',
    descriptionEn: '',
    price: 7.95,
    quantity: null
  },
  {
    id: 62,
    number: '62',
    category: 'PARA IR CON TODO',
    categoryEn: 'GO FOR IT',
    nameEs: 'Tiras de pollo agridulce',
    nameEn: 'Sweet & Sour chicken strips',
    descriptionEs: '',
    descriptionEn: '',
    price: 7.95,
    quantity: null
  },
  {
    id: 63,
    number: '63',
    category: 'PARA IR CON TODO',
    categoryEn: 'GO FOR IT',
    nameEs: 'Tofu frito',
    nameEn: 'Spicy fried tofu',
    descriptionEs: 'Tofu frito agripicante',
    descriptionEn: '',
    price: 5.95,
    quantity: null
  },
  // PRINCIPALES
  {
    id: 71,
    number: '71',
    category: 'PRINCIPALES',
    categoryEn: 'MAIN DISHES',
    nameEs: 'Arroz frito',
    nameEn: 'Fried rice',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.50,
    quantity: null,
    customizable: false
  },
  {
    id: 72,
    number: '72',
    category: 'PRINCIPALES',
    categoryEn: 'MAIN DISHES',
    nameEs: 'Udón con verdura',
    nameEn: 'Udon with vegetable',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.50,
    quantity: null,
    customizable: false
  },
  {
    id: 73,
    number: '73',
    category: 'PRINCIPALES',
    categoryEn: 'MAIN DISHES',
    nameEs: 'Padthai con verdura',
    nameEn: 'Padthai with vegetable',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.50,
    quantity: null,
    customizable: true
  },
  {
    id: 74,
    number: '74',
    category: 'PRINCIPALES',
    categoryEn: 'MAIN DISHES',
    nameEs: 'Noodles con verdura',
    nameEn: 'Noodles with vegetable',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.50,
    quantity: null,
    customizable: true
  },
  // EL TOQUE FINAL
  {
    id: 81,
    number: '81',
    category: 'EL TOQUE FINAL',
    categoryEn: 'THE FINAL TOUCH',
    nameEs: 'Pastel de batata con queso',
    nameEn: 'Sweet potato with cheese',
    descriptionEs: '',
    descriptionEn: '',
    price: 6.95,
    quantity: null
  },
  // BEBIDAS
  {
    id: 91,
    number: null,
    category: 'BEBIDAS',
    categoryEn: 'DRINKS',
    nameEs: 'Agua',
    nameEn: 'Water',
    descriptionEs: '',
    descriptionEn: '',
    price: 1.50,
    quantity: null
  },
  {
    id: 92,
    number: null,
    category: 'BEBIDAS',
    categoryEn: 'DRINKS',
    nameEs: 'Agua con gas',
    nameEn: 'Sparkling water',
    descriptionEs: '',
    descriptionEn: '',
    price: 1.80,
    quantity: null
  },
  {
    id: 93,
    number: null,
    category: 'BEBIDAS',
    categoryEn: 'DRINKS',
    nameEs: 'Refrescos 500ml',
    nameEn: 'Soft Drinks',
    descriptionEs: '',
    descriptionEn: '',
    price: 2.80,
    quantity: null
  },
  {
    id: 94,
    number: null,
    category: 'BEBIDAS',
    categoryEn: 'DRINKS',
    nameEs: 'Wanglaoji (Té chino)',
    nameEn: 'Wanglaoji (Chinese ice tea)',
    descriptionEs: '',
    descriptionEn: '',
    price: 2.80,
    quantity: null
  },
  {
    id: 95,
    number: null,
    category: 'BEBIDAS',
    categoryEn: 'DRINKS',
    nameEs: 'Leche de coco',
    nameEn: 'Coconut milk',
    descriptionEs: '',
    descriptionEn: '',
    price: 2.80,
    quantity: null
  },
  {
    id: 96,
    number: null,
    category: 'BEBIDAS',
    categoryEn: 'DRINKS',
    nameEs: 'Zumos',
    nameEn: 'Juice',
    descriptionEs: '',
    descriptionEn: '',
    price: 2.20,
    quantity: null
  },
  {
    id: 97,
    number: null,
    category: 'BEBIDAS',
    categoryEn: 'DRINKS',
    nameEs: 'Café/Té',
    nameEn: 'Coffee/Tea',
    descriptionEs: '',
    descriptionEn: '',
    price: 2.00,
    quantity: null
  },
  {
    id: 98,
    number: null,
    category: 'BEBIDAS',
    categoryEn: 'DRINKS',
    nameEs: 'Cerveza Victoria',
    nameEn: 'Victoria Beer',
    descriptionEs: '',
    descriptionEn: '',
    price: 2.50,
    quantity: null
  },
  {
    id: 99,
    number: null,
    category: 'BEBIDAS',
    categoryEn: 'DRINKS',
    nameEs: 'Cerveza Victoria sin alcohol',
    nameEn: 'Victoria Beer No Alcohol',
    descriptionEs: '',
    descriptionEn: '',
    price: 2.50,
    quantity: null
  },
  {
    id: 100,
    number: null,
    category: 'BEBIDAS',
    categoryEn: 'DRINKS',
    nameEs: 'Cerveza Heineken',
    nameEn: 'Heineken Beer',
    descriptionEs: '',
    descriptionEn: '',
    price: 2.90,
    quantity: null
  },
  {
    id: 101,
    number: null,
    category: 'BEBIDAS',
    categoryEn: 'DRINKS',
    nameEs: 'Quingdao',
    nameEn: 'Quingdao Beer',
    descriptionEs: '',
    descriptionEn: '',
    price: 2.90,
    quantity: null
  }
];

